ghome_content_homepage:
    pattern:  /ghome
    defaults: { _controller: GhomeContentBundle:Default:homepage}

ghome_content_addCapteur:
    pattern: /addCapteur
    defaults: { _controller: GhomeContentBundle:Default:addCapteur }

ghome_content_addSpace:
    pattern: /addSpace
    defaults: { _controller: GhomeContentBundle:Default:addSpace }

ghome_content_listSpaces:
    pattern: /listSpaces
    defaults: { _controller: GhomeContentBundle:Default:listSpaces }

ghome_content_addContent:
    pattern: /content/{idString}
    defaults: { _controller: GhomeContentBundle:Default:content }

ghome_content_deleteSpace:
    pattern: /deleteSpace/{id}
    defaults: { _controller: GhomeContentBundle:Default:deleteSpace }