parameters:
#    ghome_content.example.class: Ghome\ContentBundle\Example

services:
#    ghome_content.example:
#        class: %ghome_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
