SET foreign_key_checks = 0;

TRUNCATE TABLE `Actionneur`;

INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,77,"1371");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,30,"0A0F");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,93,"1AE9");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,89,"AD35");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,70,"516F");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,45,"F9BC");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,82,"960E");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,23,"5064");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,87,"F674");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,90,"B166");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,61,"9D60");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,86,"743C");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,23,"1262");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,50,"EB51");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,27,"C5F3");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,45,"19C1");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,49,"94EE");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,42,"268A");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,51,"89DB");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,48,"E88F");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,69,"21D1");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,55,"2D76");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,36,"3A85");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,30,"781B");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,88,"7B87");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,17,"A0B4");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,42,"7027");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,71,"F578");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,23,"D43C");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,44,"49C2");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,28,"EA05");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,62,"C6A2");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,56,"9111");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,32,"ABEC");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,37,"2776");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,10,"2C12");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,66,"E4B7");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,78,"DCFB");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,61,"2C3B");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,2,"7102");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,83,"3118");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,98,"8673");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,57,"F616");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,4,"4F87");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,25,"2A41");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,93,"1840");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,60,"D3EB");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,54,"709D");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,96,"86F0");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,26,"9448");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,13,"CDC6");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,60,"560A");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,26,"1ACA");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,24,"98B2");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,88,"10D4");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,4,"59E6");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,95,"5EBE");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,24,"E97B");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,60,"31CA");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,86,"D232");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,100,"2DFF");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,42,"5353");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,61,"738A");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,52,"81D8");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,30,"53FD");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,12,"307B");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,66,"E9C7");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,83,"23B1");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,68,"1070");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,20,"A386");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,40,"C549");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,29,"39B7");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,45,"432B");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,17,"5BE3");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,5,"FA39");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,48,"A36A");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,78,"1F98");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,2,"64E2");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,56,"AF59");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,87,"67AE");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,72,"F927");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,47,"5A2B");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,18,"B9B2");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,18,"B27C");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,93,"C8AE");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,6,"9A22");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,36,"785C");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,95,"0EA6");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,44,"2804");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,69,"1A36");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,68,"1B30");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,26,"03EA");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,88,"9AD1");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,79,"AAD5");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,33,"E718");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (5,44,"E221");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (4,73,"6EF7");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (1,94,"D483");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (2,43,"1F1C");
INSERT IGNORE INTO `Actionneur` (`id_Etat`,`id_Espace`,`trameLearn`) VALUES (3,80,"01C4");

TRUNCATE TABLE `Capteur`;

INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (94,"0BEB");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (36,"1B4B");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (48,"E96E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (72,"9FF0");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (80,"B0E6");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (19,"E65E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (53,"75D0");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (96,"8C74");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (93,"28FD");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (13,"79EE");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (92,"3A38");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (82,"F4C4");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (94,"8576");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (48,"D6E9");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (26,"72FB");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (67,"3FC9");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (46,"5882");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (95,"1F93");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (79,"0CA7");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (13,"839E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (96,"B711");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (57,"87EE");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (22,"182A");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (21,"D161");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (84,"FD20");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (10,"16DF");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (89,"152C");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (30,"A5E4");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (83,"53B6");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (24,"E27E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (3,"4992");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (17,"7966");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (48,"AE91");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (37,"E7D4");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (53,"1084");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (98,"2A1A");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (38,"C5C4");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (3,"D779");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (5,"534E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (72,"A510");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (15,"A478");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (60,"A4DE");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (53,"3E39");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (77,"4EA2");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (75,"ACD8");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (84,"52B2");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (28,"ACD5");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (71,"36BF");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (15,"B5E6");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (11,"1E3B");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (96,"F3F8");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (1,"9071");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (60,"05D2");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (36,"954C");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (9,"8E11");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (15,"CF0C");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (94,"6A0E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (3,"63F2");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (34,"C2FE");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (4,"2619");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (3,"06DA");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (15,"28AA");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (82,"9168");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (80,"B55F");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (51,"BD12");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (87,"6169");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (61,"4EB8");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (64,"4E89");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (53,"A069");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (87,"53BA");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (27,"8365");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (99,"6F5D");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (98,"53D7");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (8,"7B38");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (3,"D980");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (59,"A997");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (45,"706E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (89,"514A");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (87,"44AA");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (93,"D713");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (10,"74A6");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (60,"7478");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (100,"7F81");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (15,"30F4");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (95,"6D8E");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (48,"CFD8");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (44,"D294");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (78,"74A4");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (30,"45A4");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (3,"D6B8");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (30,"A60D");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (5,"8301");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (85,"9658");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (83,"4AEC");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (31,"E2E7");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (30,"AF76");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (59,"17F1");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (58,"2F57");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (98,"A61F");
INSERT IGNORE INTO `Capteur` (`id_Espace`,`trameLearn`) VALUES (2,"D677");



TRUNCATE TABLE `DateHeure`;

INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8446-88-68 9:0:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9777-88-76 9:3:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0389-89-75 3:5:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5005-55-67 0:2:5");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1719-15-87 2:4:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9637-68-76 9:5:5");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0374-97-91 4:7:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1595-58-94 6:7:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2132-53-89 7:4:0");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3708-54-91 2:8:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0710-22-94 0:0:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0912-09-30 8:7:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9400-18-65 1:0:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2131-60-44 7:3:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0486-23-06 9:3:0");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3466-98-26 2:4:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8385-41-49 9:2:5");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4908-22-67 0:9:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("7101-70-92 7:8:0");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6057-20-29 9:1:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5774-87-98 4:1:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3975-17-95 2:0:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0699-53-34 9:7:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5087-63-47 7:4:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("7684-25-43 0:2:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2050-10-92 9:4:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("7357-18-39 7:7:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6514-01-31 5:5:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2055-88-95 5:8:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6909-39-40 1:9:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5810-67-88 7:7:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8047-98-03 1:0:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4672-47-44 7:9:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2295-95-19 8:6:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8603-50-52 1:7:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1766-44-43 2:4:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0012-01-68 0:7:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5398-13-92 7:2:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1643-16-93 6:6:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2561-50-88 3:4:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4141-65-60 8:2:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5049-65-20 0:5:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9641-93-93 3:3:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("7427-39-79 9:9:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3338-41-14 4:6:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1395-96-74 6:8:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4661-02-34 9:2:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("7860-92-17 3:7:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9089-01-94 1:4:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("0633-03-58 3:4:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2989-61-05 1:3:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5737-58-16 8:2:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6193-03-54 0:0:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4322-06-97 9:6:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8150-48-46 8:9:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9079-80-93 2:3:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4641-79-93 5:9:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5380-90-22 8:5:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9190-13-93 4:4:5");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6520-33-86 8:1:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4934-70-04 5:5:0");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3317-01-59 7:5:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2689-24-14 3:2:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6667-63-81 0:2:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8212-45-63 0:6:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5022-90-08 9:0:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1648-36-22 3:7:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5859-42-95 0:4:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8019-76-63 4:5:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5058-60-51 6:0:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4802-21-46 3:5:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1368-02-68 1:8:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3989-59-65 1:3:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4585-08-01 4:6:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8095-18-73 4:2:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("1513-14-49 8:7:9");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3289-15-36 5:3:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("7642-22-11 0:1:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2470-72-79 7:8:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8170-65-16 7:8:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2113-27-74 1:1:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6423-74-68 2:3:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5433-19-97 2:5:5");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3307-46-51 5:1:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3018-17-69 1:1:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9216-45-22 2:4:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6814-01-38 1:7:0");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6275-85-01 9:6:7");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4785-75-82 0:4:5");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("7769-69-33 2:2:8");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2224-19-82 3:9:3");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("5439-37-91 1:5:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("3222-67-72 1:1:1");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2338-07-72 4:8:5");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("6907-54-39 2:5:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("9699-52-25 8:2:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("2110-12-58 8:9:2");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4178-20-29 2:1:4");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("8278-57-13 9:7:6");
INSERT IGNORE INTO `DateHeure` (`dateReleve`) VALUES ("4083-23-22 8:1:3");

TRUNCATE TABLE `Espace`;

INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Lesotho","a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Switzerland","non enim commodo hendrerit. Donec porttitor tellus non magna. Nam",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guinea-Bissau","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Peru","Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Philippines","et netus et malesuada fames ac turpis egestas. Fusce aliquet",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Pitcairn Islands","quam. Pellentesque habitant morbi tristique senectus et netus et malesuada",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Antarctica","augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel,",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Wallis and Futuna","lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saudi Arabia","amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Netherlands","pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Croatia","tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Honduras","porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Andorra","et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Yemen","id, blandit at, nisi. Cum sociis natoque penatibus et magnis",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Bermuda","In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Egypt","Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Kiribati","nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Peru","risus. Nulla eget metus eu erat semper rutrum. Fusce dolor",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Croatia","amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Nicaragua","Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Helena, Ascension and Tristan da Cunha","quis diam. Pellentesque habitant morbi tristique senectus et netus et",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Burundi","nisi. Cum sociis natoque penatibus et magnis dis parturient montes,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Lebanon","non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Lucia","iaculis enim, sit amet ornare lectus justo eu arcu. Morbi",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Kitts and Nevis","tortor at risus. Nunc ac sem ut dolor dapibus gravida.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Somalia","vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Togo","amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Nepal","nunc. In at pede. Cras vulputate velit eu sem. Pellentesque",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("United States","diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Antarctica","eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Dominica","dictum augue malesuada malesuada. Integer id magna et ipsum cursus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guyana","enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Dominican Republic","Curabitur egestas nunc sed libero. Proin sed turpis nec mauris",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Marshall Islands","tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Kuwait","sit amet ultricies sem magna nec quam. Curabitur vel lectus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Belgium","orci, in consequat enim diam vel arcu. Curabitur ut odio",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Laos","in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Jersey","nulla. Donec non justo. Proin non massa non ante bibendum",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Niue","convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Italy","Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Latvia","ipsum sodales purus, in molestie tortor nibh sit amet orci.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Papua New Guinea","Nulla eget metus eu erat semper rutrum. Fusce dolor quam,",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Tokelau","non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Micronesia","parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Bouvet Island","vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Latvia","commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac,",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Armenia","tellus faucibus leo, in lobortis tellus justo sit amet nulla.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Maldives","in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Comoros","ornare. Fusce mollis. Duis sit amet diam eu dolor egestas",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sweden","enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Switzerland","lectus convallis est, vitae sodales nisi magna sed dui. Fusce",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Eritrea","est, vitae sodales nisi magna sed dui. Fusce aliquam, enim",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Malawi","ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Morocco","semper egestas, urna justo faucibus lectus, a sollicitudin orci sem",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Singapore","Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Iraq","libero lacus, varius et, euismod et, commodo at, libero. Morbi",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("French Guiana","vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Moldova","metus urna convallis erat, eget tincidunt dui augue eu tellus.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guernsey","enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Brazil","non enim. Mauris quis turpis vitae purus gravida sagittis. Duis",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Kuwait","ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Portugal","Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper,",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Austria","eros non enim commodo hendrerit. Donec porttitor tellus non magna.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("South Sudan","sed libero. Proin sed turpis nec mauris blandit mattis. Cras",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Trinidad and Tobago","magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Turks and Caicos Islands","erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Hungary","Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Maldives","posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Philippines","magna a neque. Nullam ut nisi a odio semper cursus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sudan","Pellentesque habitant morbi tristique senectus et netus et malesuada fames",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Solomon Islands","pellentesque, tellus sem mollis dui, in sodales elit erat vitae",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Lebanon","at arcu. Vestibulum ante ipsum primis in faucibus orci luctus",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Burkina Faso","diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("French Guiana","dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Turks and Caicos Islands","non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Algeria","amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("United States","sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Burundi","Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sao Tome and Principe","et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Australia","augue, eu tempor erat neque non quam. Pellentesque habitant morbi",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Taiwan","Cum sociis natoque penatibus et magnis dis parturient montes, nascetur",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Cook Islands","urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Djibouti","Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Maldives","montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Oman","Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Namibia","tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Palestine, State of","et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Antarctica","bibendum fermentum metus. Aenean sed pede nec ante blandit viverra.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Andorra","mattis semper, dui lectus rutrum urna, nec luctus felis purus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Swaziland","ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate,",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Bouvet Island","Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Oman","sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Eritrea","vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sint Maarten","Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guinea","imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Pierre and Miquelon","nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Nicaragua","auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Japan","velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Equatorial Guinea","eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Algeria","blandit at, nisi. Cum sociis natoque penatibus et magnis dis",2);

TRUNCATE TABLE `Espace`;

INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Lesotho","a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Switzerland","non enim commodo hendrerit. Donec porttitor tellus non magna. Nam",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guinea-Bissau","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Peru","Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Philippines","et netus et malesuada fames ac turpis egestas. Fusce aliquet",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Pitcairn Islands","quam. Pellentesque habitant morbi tristique senectus et netus et malesuada",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Antarctica","augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel,",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Wallis and Futuna","lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saudi Arabia","amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Netherlands","pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Croatia","tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Honduras","porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Andorra","et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Yemen","id, blandit at, nisi. Cum sociis natoque penatibus et magnis",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Bermuda","In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Egypt","Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Kiribati","nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Peru","risus. Nulla eget metus eu erat semper rutrum. Fusce dolor",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Croatia","amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Nicaragua","Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Helena, Ascension and Tristan da Cunha","quis diam. Pellentesque habitant morbi tristique senectus et netus et",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Burundi","nisi. Cum sociis natoque penatibus et magnis dis parturient montes,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Lebanon","non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Lucia","iaculis enim, sit amet ornare lectus justo eu arcu. Morbi",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Kitts and Nevis","tortor at risus. Nunc ac sem ut dolor dapibus gravida.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Somalia","vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Togo","amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Nepal","nunc. In at pede. Cras vulputate velit eu sem. Pellentesque",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("United States","diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Antarctica","eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Dominica","dictum augue malesuada malesuada. Integer id magna et ipsum cursus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guyana","enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Dominican Republic","Curabitur egestas nunc sed libero. Proin sed turpis nec mauris",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Marshall Islands","tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Kuwait","sit amet ultricies sem magna nec quam. Curabitur vel lectus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Belgium","orci, in consequat enim diam vel arcu. Curabitur ut odio",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Laos","in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Jersey","nulla. Donec non justo. Proin non massa non ante bibendum",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Niue","convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Italy","Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Latvia","ipsum sodales purus, in molestie tortor nibh sit amet orci.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Papua New Guinea","Nulla eget metus eu erat semper rutrum. Fusce dolor quam,",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Tokelau","non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Micronesia","parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Bouvet Island","vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Latvia","commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac,",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Armenia","tellus faucibus leo, in lobortis tellus justo sit amet nulla.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Maldives","in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Comoros","ornare. Fusce mollis. Duis sit amet diam eu dolor egestas",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sweden","enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Switzerland","lectus convallis est, vitae sodales nisi magna sed dui. Fusce",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Eritrea","est, vitae sodales nisi magna sed dui. Fusce aliquam, enim",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Malawi","ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Morocco","semper egestas, urna justo faucibus lectus, a sollicitudin orci sem",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Singapore","Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Iraq","libero lacus, varius et, euismod et, commodo at, libero. Morbi",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("French Guiana","vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Moldova","metus urna convallis erat, eget tincidunt dui augue eu tellus.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guernsey","enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Brazil","non enim. Mauris quis turpis vitae purus gravida sagittis. Duis",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Kuwait","ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Portugal","Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper,",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Austria","eros non enim commodo hendrerit. Donec porttitor tellus non magna.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("South Sudan","sed libero. Proin sed turpis nec mauris blandit mattis. Cras",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Trinidad and Tobago","magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Turks and Caicos Islands","erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Hungary","Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Maldives","posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Philippines","magna a neque. Nullam ut nisi a odio semper cursus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sudan","Pellentesque habitant morbi tristique senectus et netus et malesuada fames",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Solomon Islands","pellentesque, tellus sem mollis dui, in sodales elit erat vitae",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Lebanon","at arcu. Vestibulum ante ipsum primis in faucibus orci luctus",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Burkina Faso","diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("French Guiana","dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Turks and Caicos Islands","non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Algeria","amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("United States","sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Burundi","Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sao Tome and Principe","et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Australia","augue, eu tempor erat neque non quam. Pellentesque habitant morbi",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Taiwan","Cum sociis natoque penatibus et magnis dis parturient montes, nascetur",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Cook Islands","urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Djibouti","Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Maldives","montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Oman","Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Namibia","tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Palestine, State of","et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat",2);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Antarctica","bibendum fermentum metus. Aenean sed pede nec ante blandit viverra.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Andorra","mattis semper, dui lectus rutrum urna, nec luctus felis purus",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Swaziland","ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate,",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Bouvet Island","Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Oman","sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Eritrea","vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Sint Maarten","Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis",1);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Guinea","imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Saint Pierre and Miquelon","nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc.",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Nicaragua","auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus,",5);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Japan","velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus.",3);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Equatorial Guinea","eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet",4);
INSERT IGNORE INTO `Espace` (`nom`,`description`,`id_TypeSpace`) VALUES ("Algeria","blandit at, nisi. Cum sociis natoque penatibus et magnis dis",2);

TRUNCATE TABLE `Etat`;

INSERT IGNORE INTO `Etat` (`label`,`description`) VALUES ("tincidunt pede","nisl. Quisque fringilla euismod enim.");
INSERT IGNORE INTO `Etat` (`label`,`description`) VALUES ("a mi","nisi sem semper");
INSERT IGNORE INTO `Etat` (`label`,`description`) VALUES ("semper auctor.","Nulla eget metus eu erat");
INSERT IGNORE INTO `Etat` (`label`,`description`) VALUES ("ac risus.","Suspendisse eleifend. Cras sed");
INSERT IGNORE INTO `Etat` (`label`,`description`) VALUES ("aliquam iaculis,","vel est tempor bibendum.");

TRUNCATE TABLE `Propriete`;

INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (58,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (15,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (84,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (59,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (30,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (82,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (19,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (73,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (7,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (60,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (70,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (8,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (1,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (38,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (70,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (69,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (24,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (79,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (17,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (41,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (2,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (51,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (56,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (23,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (75,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (67,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (70,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (70,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (59,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (42,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (28,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (23,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (49,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (29,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (6,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (100,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (99,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (27,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (13,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (13,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (27,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (38,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (41,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (82,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (58,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (43,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (49,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (34,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (75,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (15,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (37,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (14,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (98,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (57,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (10,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (56,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (74,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (82,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (56,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (66,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (45,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (77,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (22,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (95,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (56,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (11,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (63,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (76,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (45,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (8,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (100,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (93,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (6,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (82,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (88,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (30,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (61,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (5,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (84,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (28,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (66,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (78,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (56,5);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (24,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (46,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (36,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (13,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (65,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (21,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (78,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (1,3);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (14,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (79,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (58,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (36,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (51,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (28,1);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (14,2);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (11,4);
INSERT IGNORE INTO `Propriete` (`id_capteur`,`id_TypePropriete`) VALUES (54,4);

TRUNCATE TABLE `Relever`;

INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (533,24,18);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (683,81,91);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (612,46,92);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (552,34,8);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (644,3,12);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (569,96,19);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (413,69,46);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (927,6,94);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (349,34,62);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (884,28,64);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (113,91,49);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (384,74,95);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (452,26,21);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (984,15,40);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (49,23,92);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (476,30,7);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (429,52,13);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (835,79,70);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (897,54,1);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (925,85,25);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (16,92,21);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (852,90,64);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (11,98,12);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (238,44,74);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (539,22,81);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (447,71,19);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (244,73,88);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (660,57,100);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (339,24,21);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (28,55,29);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (370,50,40);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (186,34,76);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (608,27,16);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (932,28,67);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (134,65,63);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (839,56,98);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (792,75,63);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (281,87,92);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (975,26,57);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (942,56,91);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (670,88,41);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (690,32,8);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (870,18,83);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (903,2,14);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (592,1,71);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (261,9,28);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (776,32,34);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (16,78,49);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (104,12,99);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (441,10,38);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (346,89,69);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (400,4,88);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (249,44,2);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (437,72,27);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (200,63,15);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (323,74,28);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (714,54,79);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (944,71,43);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (151,90,59);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (113,30,52);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (398,81,17);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (645,93,57);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (328,91,24);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (804,47,65);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (862,72,78);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (397,32,16);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (623,40,85);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (502,46,17);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (133,30,59);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (611,23,40);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (975,84,82);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (624,4,32);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (280,24,8);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (304,84,56);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (894,6,46);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (105,3,75);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (569,10,66);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (82,2,80);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (592,88,3);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (438,3,30);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (342,14,100);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (74,85,25);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (203,50,31);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (671,27,4);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (444,89,93);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (585,38,64);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (958,36,91);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (803,80,89);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (939,4,59);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (574,1,2);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (270,71,99);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (360,33,45);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (291,39,100);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (986,100,27);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (665,7,39);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (762,6,6);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (148,12,79);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (955,69,12);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (964,90,94);
INSERT IGNORE INTO `Relever` (`valeur`,`id_Propriete`,`id_DateHeure`) VALUES (523,73,19);

TRUNCATE TABLE `TrameLearn`;

INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("0EBB",1);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("56CE",2);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("34EE",3);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("06CF",4);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("4DE8",5);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("5C66",6);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("CDFD",7);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("9014",8);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("8A7C",9);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("18DB",10);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("01DE",11);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("EFC2",12);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C698",13);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("A048",14);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("7C35",15);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("CAEF",16);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("70F2",17);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("34D7",18);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("33F0",19);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("A8B6",20);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("7256",21);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("F155",22);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("AA51",23);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("AB01",24);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("437B",25);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("556A",26);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("2310",27);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("95AF",28);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("BF4F",29);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("EECA",30);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("820E",31);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("1AD1",32);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("BFC3",33);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("4402",34);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("4414",35);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("5F30",36);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("EE2E",37);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("090A",38);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C2F2",39);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("693B",40);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("F4F5",41);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("FE3C",42);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C118",43);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("5A4F",44);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("F535",45);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("096C",46);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("CC44",47);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("EBAF",48);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("325F",49);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("F572",50);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("1743",51);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("DEB5",52);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("A13D",53);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("959F",54);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("7DB9",55);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C3C8",56);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("4454",57);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("4F15",58);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("8CC3",59);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("2F21",60);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("EFEE",61);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C8DF",62);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("7913",63);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("8F37",64);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("9512",65);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("1558",66);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("CCA0",67);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("D56F",68);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("5AB9",69);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("F76B",70);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("245F",71);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C689",72);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("D5A5",73);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("1EB7",74);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("2019",75);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("93E4",76);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("5784",77);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("EAB0",78);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("974C",79);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("D787",80);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("319C",81);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("700F",82);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C687",83);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("8B81",84);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("CD17",85);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("7BF3",86);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("9F1B",87);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("467B",88);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("867C",89);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("52C6",90);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("E659",91);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("3D6A",92);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("DF52",93);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("D547",94);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("51D5",95);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("E748",96);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("CC6F",97);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("4780",98);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("6C47",99);
INSERT IGNORE INTO `TrameLearn` (`trame`,`idPhysiqueCapteur`) VALUES ("C50D",100);

TRUNCATE TABLE `TypePropriete`;

INSERT IGNORE INTO `TypePropriete` (`label`) VALUES ("eleifend nec,");
INSERT IGNORE INTO `TypePropriete` (`label`) VALUES ("ipsum. Phasellus");
INSERT IGNORE INTO `TypePropriete` (`label`) VALUES ("Proin ultrices.");
INSERT IGNORE INTO `TypePropriete` (`label`) VALUES ("vulputate velit");
INSERT IGNORE INTO `TypePropriete` (`label`) VALUES ("congue turpis.");

TRUNCATE TABLE `TypeSpace`;

INSERT IGNORE INTO `TypeSpace` (`label`,`description`) VALUES ("arcu. Nunc","ac mi eleifend egestas. Sed");
INSERT IGNORE INTO `TypeSpace` (`label`,`description`) VALUES ("est, vitae","Cras eget nisi dictum augue");
INSERT IGNORE INTO `TypeSpace` (`label`,`description`) VALUES ("pellentesque massa","Fusce aliquet magna a neque.");
INSERT IGNORE INTO `TypeSpace` (`label`,`description`) VALUES ("erat vel","urna. Nunc quis arcu vel");
INSERT IGNORE INTO `TypeSpace` (`label`,`description`) VALUES ("Duis dignissim","lectus ante dictum mi, ac");


SET foreign_key_checks = 1;
